function filart(a,b){var d;b=b.toUpperCase();var c=document.getElementById(a).getElementsByTagName("tr");if("tbdvrgvp"===a){var e=8;var f=6}else e=6,f=2;for(d=1;d<c.length;d++){var g=c[d].getElementsByTagName("td")[f];if("tbdvrgvp"===a){var h=c[d].getElementsByTagName("td")[f];var k=c[d].getElementsByTagName("td")[f]}else h=c[d].getElementsByTagName("td")[3],k=c[d].getElementsByTagName("td")[5];var l=c[d].getElementsByTagName("td")[e];if(g){g=g.textContent||g.innerText;h=h.textContent||h.innerText;
k=k.textContent||k.innerText;l=l.textContent||l.innerText;if(null===g||""===g)g="_";if(null===h||""===h)h="_";if(null===k||""===k)k="_";if(null===l||""===l)l="_";if(-1<g.toUpperCase().indexOf(b)||-1<h.toUpperCase().indexOf(b)||-1<k.toUpperCase().indexOf(b)||-1<l.toUpperCase().indexOf(b)){c[d].style.visibility="";try{c[1].parentNode.insertBefore(c[d],c[1])}catch(m){}}else c[d].style.visibility="hidden"}}}
function filart1vl(a,b){var d,c;b=b.toUpperCase();a=document.getElementById(a).getElementsByTagName("tr");for(c=1;c<a.length;c++)if(d=a[c].getElementsByTagName("td")[1]){d=d.textContent||d.innerText;if(null===d||""===d)d="_";if(-1<d.toUpperCase().indexOf(b)){a[c].style.visibility="";try{a[1].parentNode.insertBefore(a[c],a[1])}catch(e){}}else a[c].style.visibility="hidden"}}
function disabclntnrinf(){if(1===document.getElementById("msnmbr").innerHTML.trim().length){try{gbtninsrtpedvend="1"}catch(a){}try{gbtnPedIns="1"}catch(a){}try{gbtnpdrpag="1"}catch(a){}}}function processdescount(a){a=Number(a);var b=Number(document.getElementById("vend_quant").value);a=-.01*Number(a)*lastartprc*b;document.getElementById("vend_prc").value=""+FixDecToTwo(a);document.getElementById("spvendtp").innerHTML="Fazendo desconto!";document.getElementById("spvendtp").style.color="green"}
function fVInR(a){table=document.getElementById("tbdvrv");for(var b=table.rows,d=1;d<b.length;d++)for(var c=b[d].cells,e=0;e<c.length;e++)if(c[e].innerText===a)return!0;return!1}function ValQuantDscnt(a){var b=0;table=document.getElementById("tbdvrv");for(var d=table.rows,c=1;c<d.length;c++){var e=d[c].cells;if(e[6].innerText===a){var f=0;try{f=Number(e[7].innerText)}catch(g){f=0}b+=f}}return b}
function getdpstvls(){var a=document.getElementById("dpst_clientname").value,b=document.getElementById("dpst_residenty").value,d=document.getElementById("dpst_id_number").value,c=document.getElementById("dpst_phone").value,e=document.getElementById("dpst_observation").value;return"&c="+a+"&r="+b+"&i="+d+"&p="+c+"&o="+e}function addartonthefly(a){var b=document.getElementById("lst_prod");try{var d=document.createElement("option");d.value=a;b.appendChild(d)}catch(c){}}
function addartonthefly2(a){var b=document.getElementById("lst_prod2");try{var d=document.createElement("option");d.value=a;b.appendChild(d)}catch(c){}}function addfctryonthefly(a){var b=document.getElementById("lst_grp");try{var d=document.createElement("option");d.value=a;b.appendChild(d)}catch(c){}}
function stvalc(a){if("v"===a){slsalc="v";try{document.getElementById("strngvnd").innerHTML="Vendas"}catch(b){}}else if("a"===a){slsalc="c";try{document.getElementById("strngvnd").innerHTML="Aloca&ccedil;&otilde;es"}catch(b){}}}
function tdstck(a,b,d,c){c||(c=window.event);c.cancelBubble=!0;c.stopPropagation&&c.stopPropagation();try{c="0","Sim"===b&&(c="1"),document.getElementById("stkcusd"+a).innerHTML="<select onchange=\"processar('"+d+"', 'stkalc')\"><option value=\""+c+'">'+b+'</option><option value="1">Sim</option></select>'}catch(e){alert(e.message)}try{document.getElementById("stkcusd"+a).removeAttribute("onclick")}catch(e){}}function desabledelement(){alert("Recurso indisponivel!")}
function rnfb(a){"b"===a?nrfb="b":"f"===a&&(nrfb="f")}function nmbrofrecds(a){var b="0",d="";try{d=document.getElementById("rwsintbls").value;var c=document.getElementById("tbdvr"+a);b=""+c.rows[c.rows.length-1].cells[0].innerHTML;1>c.rows.length-1&&(b="0")}catch(e){}a=nrfb;nrfb="z";c=document.getElementById("yesnodlt").value;return"&nlstid="+b+"&nrws="+d+"&nfb="+a+"&yesnodlt="+c}
function calculatechg(){var a=document.getElementById("pago").value;var b=0;try{b=parseFloat(a)}catch(d){b=0}a=b-smvlsglb;a=a.toFixed(2);0<a?document.getElementById("troco").style.backgroundColor="green":document.getElementById("troco").style.backgroundColor="red";document.getElementById("troco").innerHTML=""+a}function rplcSpcialChar(a){var b;try{for(var d=a.length,c=0;c<d;c++){var e=a.charAt(c);b+=""+bsccaresp(e)}}catch(f){}return b}
function bsccaresp(a){var b="";if(null===a||"&"!==a&&!b.includes("&")){if(null===a||":"!==a&&!b.includes("&"))return a;try{b=d=a.replace(":","_")}catch(c){}return b}try{var d=a.replace("&","_");b=d}catch(c){}return b}function setArticle(a,b){if("lstprdvendas"===a)try{document.getElementById("vend_art").value=b,getCodBarCode(b,"v")}catch(d){}else if("lstprdpedvendas"===a)try{document.getElementById("pedvend_art").value=b,getCodBarCode(b,"pedv")}catch(d){}}
function checklstofms(){clickedlstreqvend="yes"}function checklstofmsno(){clickedlstreqvend="no"}function FixDecToTwo(a){a=""+a;if(null===a||""===a)return a;if(a.includes(".")){var b=a.split(".");a=b[0];b=b[1];var d="",c="";try{d=b.charAt(0)}catch(e){d=""}try{c=b.charAt(1)}catch(e){c=""}return a+"."+d+c}return a+".00"}
function filbyclnsnr(a,b,d,c,e,f){var g,h=0,k=0,l=0,m=0;b=b.toUpperCase();a=document.getElementById(a).getElementsByTagName("tr");for(g=1;g<a.length;g++){var n=a[g].getElementsByTagName("td")[d];var q=a[g].getElementsByTagName("td")[c];var r=a[g].getElementsByTagName("td")[e];if(n){n=n.textContent||n.innerText;q=q.textContent||q.innerText;r=r.textContent||r.innerText;if(null===n||""===n)n="_";if(null===q||""===q)q="_";if(null===r||""===r)r="_";if(-1<n.toUpperCase().indexOf(b)||-1<q.toUpperCase().indexOf(b)||
-1<r.toUpperCase().indexOf(b)){a[g].style.visibility="";try{a[1].parentNode.insertBefore(a[g],a[1])}catch(t){}try{m+=1,"va"===f?(h+=parseFloat(a[1].getElementsByTagName("td")[10].innerHTML),k+=parseFloat(a[1].getElementsByTagName("td")[11].innerHTML)):"c"===f?(h+=parseFloat(a[1].getElementsByTagName("td")[8].innerHTML),k+=parseFloat(a[1].getElementsByTagName("td")[12].innerHTML)):"d"===f?h+=parseFloat(a[1].getElementsByTagName("td")[2].innerHTML):"dpst"===f&&(h+=parseFloat(a[1].getElementsByTagName("td")[7].innerHTML),
k+=parseFloat(a[1].getElementsByTagName("td")[8].innerHTML),l+=parseFloat(a[1].getElementsByTagName("td")[9].innerHTML))}catch(t){}}else a[g].style.visibility="hidden"}}"va"===f?document.getElementById("tbdvrvasum").innerHTML="Total: "+FixDecToTwo(h)+" Mts, Lucro(est): "+FixDecToTwo(k)+" Mts, Registos: "+m:"c"===f?document.getElementById("tbdvrcsum").innerHTML="Total: "+FixDecToTwo(h)+" Mts, Lucro(est): "+FixDecToTwo(k)+" Mts, Registos: "+m:"d"===f?document.getElementById("tbdvrdsum").innerHTML="Total: "+
FixDecToTwo(h)+" Mts, Registos: "+m:"dpst"===f&&(document.getElementById("tbdvrdptsum").innerHTML="Total Deposito: "+FixDecToTwo(h)+" Mts, Total Usado: "+FixDecToTwo(k)+" Mts, <strong>Total Saldo: "+FixDecToTwo(l)+" Mts</strong>, Registos: "+m)}
function aborginf(){try{document.getElementById("chcklogt").disabled=!1}catch(a){}try{document.getElementById("txtdesig").disabled=!1}catch(a){}try{document.getElementById("chckdesig").disabled=!1}catch(a){}try{document.getElementById("txtlocz").disabled=!1}catch(a){}try{document.getElementById("chcklocz").disabled=!1}catch(a){}try{document.getElementById("btndesloc").disabled=!1}catch(a){}try{document.getElementById("fllogt").disabled=!1}catch(a){}}
function enablesysidpwd(){try{document.getElementById("txtsysid").disabled=!1}catch(a){}try{document.getElementById("txtsyspwd").disabled=!1}catch(a){}}
function desaborginf(){try{document.getElementById("chcklogt").disabled=!0}catch(a){}try{document.getElementById("txtdesig").disabled=!0}catch(a){}try{document.getElementById("chckdesig").disabled=!0}catch(a){}try{document.getElementById("txtlocz").disabled=!0}catch(a){}try{document.getElementById("chcklocz").disabled=!0}catch(a){}try{document.getElementById("btndesloc").disabled=!0}catch(a){}try{document.getElementById("fllogt").disabled=!0}catch(a){}}
function getsysidpwd(){var a=document.getElementById("txtsysid").value,b=document.getElementById("txtsyspwd").value;return"&idsys="+a+"&pwdsys="+b}function chklgc(a){var b="0";try{b=!0===a.checked?"1":"0"}catch(d){}return b}function startlookstate(){IntervalSrvrChk=setInterval(checkstatestutus2(),1E3)}function stoplookstate(){try{clearInterval(IntervalSrvrChk)}catch(a){}}function checkstatestutus2(){setTimeout(function(){checkstatestutus()},500)}
function getCodBarCode(a,b){p=b;document.getElementById("spvendtp").innerHTML="Venda normal!";document.getElementById("spvendtp").style.color="blue";processar(a,"cdbar")}
function fillProdCodBar(a){var b=a.split(",");a=b[0];var d=b[1],c=b[2],e=b[3],f=b[4],g=b[5],h=b[6],k=b[7];b=b[8];document.getElementById("spdescount");lastartprc=parseFloat(h);"v"===p?(document.getElementById("vend_pcod").value=a,document.getElementById("vend_cbar").value=d,document.getElementById("vend_grp").value=c,document.getElementById("vend_tp").value=e,document.getElementById("vend_cat").value=f,document.getElementById("vend_art").value=g,document.getElementById("vend_prc").value=h,document.getElementById("vend_quant").value=
"1",lstpurcqty=b,fVInR(g)?document.getElementById("spdescount").innerHTML=k:"c"===slsalc&&(document.getElementById("spvendtp").innerHTML="Aloca&ccedil;&otilde;es!",document.getElementById("spdescount").innerHTML="Stock:<input type='number' id='txtstck' min='1' max='10' style='width: 80px;'/>")):"pedv"===p?(document.getElementById("pedvend_pcod").value=a,document.getElementById("pedvend_cbar").value=d,document.getElementById("pedvend_grp").value=c,document.getElementById("pedvend_tp").value=e,document.getElementById("pedvend_cat").value=
f,document.getElementById("pedvend_art").value=g,document.getElementById("pedvend_prc").value=h,document.getElementById("pedvend_quant").value="1",lstpurcqty=b):"c"===p?(document.getElementById("comp_pcod").value=a,document.getElementById("comp_cbar").value=d,document.getElementById("comp_grp").value=c,document.getElementById("comp_tp").value=e,document.getElementById("comp_cat").value=f,document.getElementById("comp_art").value=g):"ci"===p&&(document.getElementById("comp_pcodinv").value=a,document.getElementById("comp_cbarinv").value=
d,document.getElementById("comp_grpinv").value=c,document.getElementById("comp_tpinv").value=e,document.getElementById("comp_catinv").value=f,document.getElementById("comp_artinv").value=g,lstpurcqty=b);p="a"}function deleterped(){var a=document.getElementById("dvrpedartins2").rows;try{for(var b=0;3>b;b++)for(var d=0;d<a.length;d++)try{a[d].deleteCell(b)}catch(c){}}catch(c){}}
function checkcpb(a){"crdo_art"===a?(document.getElementById("crdo_prod").checked=!1,document.getElementById("crdo_bar").checked=!1,document.getElementById("comp_art").disabled=!1,document.getElementById("comp_pcod").disabled=!0,document.getElementById("comp_cbar").disabled=!0,document.getElementById("comp_art").value="",document.getElementById("comp_pcod").value="",document.getElementById("comp_cbar").value=""):"crdo_prod"===a?(document.getElementById("crdo_art").checked=!1,document.getElementById("crdo_bar").checked=
!1,document.getElementById("comp_art").disabled=!0,document.getElementById("comp_pcod").disabled=!1,document.getElementById("comp_cbar").disabled=!0,document.getElementById("comp_art").value="",document.getElementById("comp_pcod").value="",document.getElementById("comp_cbar").value=""):"crdo_bar"===a&&(document.getElementById("crdo_art").checked=!1,document.getElementById("crdo_prod").checked=!1,document.getElementById("comp_art").disabled=!0,document.getElementById("comp_pcod").disabled=!0,document.getElementById("comp_cbar").disabled=
!1,document.getElementById("comp_art").value="",document.getElementById("comp_pcod").value="",document.getElementById("comp_cbar").value="");"vrdo_art"===a?(document.getElementById("vrdo_prod").checked=!1,document.getElementById("vrdo_bar").checked=!1,document.getElementById("vend_art").disabled=!1,document.getElementById("vend_pcod").disabled=!0,document.getElementById("vend_cbar").disabled=!0,document.getElementById("vend_art").value="",document.getElementById("vend_pcod").value="",document.getElementById("vend_cbar").value=
""):"vrdo_prod"===a?(document.getElementById("vrdo_art").checked=!1,document.getElementById("vrdo_bar").checked=!1,document.getElementById("vend_art").disabled=!0,document.getElementById("vend_pcod").disabled=!1,document.getElementById("vend_cbar").disabled=!0,document.getElementById("vend_art").value="",document.getElementById("vend_pcod").value="",document.getElementById("vend_cbar").value=""):"vrdo_bar"===a&&(document.getElementById("vrdo_art").checked=!1,document.getElementById("vrdo_prod").checked=
!1,document.getElementById("vend_art").disabled=!0,document.getElementById("vend_pcod").disabled=!0,document.getElementById("vend_cbar").disabled=!1,document.getElementById("vend_art").value="",document.getElementById("vend_pcod").value="",document.getElementById("vend_cbar").value="");"pedvrdo_art"===a?(document.getElementById("pedvrdo_prod").checked=!1,document.getElementById("pedvrdo_bar").checked=!1,document.getElementById("pedvend_art").disabled=!1,document.getElementById("pedvend_pcod").disabled=
!0,document.getElementById("pedvend_cbar").disabled=!0,document.getElementById("pedvend_art").value="",document.getElementById("pedvend_pcod").value="",document.getElementById("pedvend_cbar").value=""):"pedvrdo_prod"===a?(document.getElementById("pedvrdo_art").checked=!1,document.getElementById("pedvrdo_bar").checked=!1,document.getElementById("pedvend_art").disabled=!0,document.getElementById("pedvend_pcod").disabled=!1,document.getElementById("pedvend_cbar").disabled=!0,document.getElementById("pedvend_art").value=
"",document.getElementById("pedvend_pcod").value="",document.getElementById("pedvend_cbar").value=""):"pedvrdo_bar"===a&&(document.getElementById("pedvrdo_art").checked=!1,document.getElementById("pedvrdo_prod").checked=!1,document.getElementById("pedvend_art").disabled=!0,document.getElementById("pedvend_pcod").disabled=!0,document.getElementById("pedvend_cbar").disabled=!1,document.getElementById("pedvend_art").value="",document.getElementById("pedvend_pcod").value="",document.getElementById("pedvend_cbar").value=
"")}
function pedvendary(){if("1"===gbtninsrtpedvend)return desabledelement(),!1;var a=document.getElementById("pedvend_tp").value,b=document.getElementById("pedvend_cat").value,d=document.getElementById("pedvend_quant").value,c=document.getElementById("pedvend_art").value,e=document.getElementById("pedvend_prc").value,f=document.getElementById("pedvend_grp").value,g=document.getElementById("pedvend_pcod").value,h=document.getElementById("pedvend_cbar").value,k=document.getElementById("msnmbr").innerHTML;"NA"!==
a&&"NA"!==b&&"0"!==d&&"NA"!==c&&"0.0"!==e&&""!==g&&""!==h&&processar("msn="+k+"&vg="+f+"&vt="+a+"&vc="+b+"&va="+c+"&vq="+d+"&vp="+e+"&vcod="+g+"&vcbar="+h+"&lstpurcqty="+lstpurcqty,"pedartins")}function setfr(a,b){document.getElementById("msst"+a).innerHTML="Pendente";document.getElementById("msnmb"+a).style.backgroundColor="#F5B041"}
function rqifmart(a){a=a.split(":");try{for(var b=0;b<a.length;b++)if(null!==a[b].split(";")[1]&&"undefined"!==a[b].split(";")[1]&&"undefined"!==typeof a[b].split(";")[1]&&""!==a[b].split(";")[1]){var d=a[b].split(";")[1],c=a[b].split(";")[2],e=a[b].split(";")[3],f=a[b].split(";")[4],g=a[b].split(";")[5],h=a[b].split(";")[6],k=a[b].split(";")[7],l=a[b].split(";")[8],m=a[b].split(";")[9],n=a[b].split(";")[10],q=m+";"+n,r=""+document.getElementById("idc").innerHTML,t=document.getElementById("clientanome").value;
vndits[b]=",vcod="+d+",vcbar="+c+",vg="+e+",vt="+f+",vc="+g+",va="+h+",vq="+k+",vp="+l+",clt="+r+",nm="+t+",pcsartcnt="+q+",txtstck=0,slsalc="+slsalc+":"}}catch(u){}rfrsh_vnd();document.getElementById("dvrst").innerHTML="<span style='color: green;'>Venda adicionada!</span>";sumvaluesforeachtbl("v")}
function prcnmbrrq(a){reqnmber=""+a;reqnmber2=""+a;reqnmber3="b";try{document.getElementById("txtdescnt").value=""}catch(b){}try{document.getElementById("spvendtp").innerHTML="Venda normal!",document.getElementById("spvendtp").style.color="blue"}catch(b){}}function rmrrg(a,b,d){rr=d;processar(b,"r"+a)}function lvlrmv(){return"&r="+rr}
function alwupdt(a){document.getElementById("guid"+a+"4").innerHTML='<select id="ipt'+a+'4" style="width: 90px;"><option value="'+document.getElementById("guid"+a+"4").innerHTML+'">'+document.getElementById("guid"+a+"4").innerHTML+'</option><option value="Gestor">Gestor</option><option value="Caixa">Caixa</option><option value="Visualizador">Visualizador</option></select>';document.getElementById("guid"+a+"5").innerHTML='<input type="text" id="ipt'+a+'5" value="'+document.getElementById("guid"+a+
"5").innerHTML+'" style="width: 180px;">';document.getElementById("guid"+a+"6").innerHTML='<input type="text" id="ipt'+a+'6" value="'+document.getElementById("guid"+a+"6").innerHTML+'" style="width: 40px;">';try{document.getElementById("btnusredit"+a).disabled=!0}catch(b){}}function csedit(a){return"&id="+a+"&c="+document.getElementById("ipt"+a+"4").value+"&p="+document.getElementById("ipt"+a+"5").value+"&e="+document.getElementById("ipt"+a+"6").value}
function dhschrts(a,b,d,c,e){new Chart(document.getElementById("brchrt"),{type:"bar",data:{labels:["Despesas","Compras","Vendas"],datasets:[{label:"Mts",backgroundColor:["#8e5ea2","#3cba9f","#e8c3b9"],data:a}]},options:{legend:{display:!1},title:{display:!0,text:"Valores por Categoria"}}});new Chart(document.getElementById("lnchrt"),{type:"line",data:{labels:e,datasets:[{data:b,label:"Despesas",borderColor:"#3e95cd",fill:!1},{data:d,label:"Compras",borderColor:"#8e5ea2",fill:!1},{data:c,label:"Vendas",
borderColor:"#3cba9f",fill:!1}]},options:{title:{display:!0,text:"Valores por Categoria e Tempo"}}})}function chmrcmplstprdpz(a){var b=document.getElementById("cmplstprd");b.style.display="block";var d=event.clientX,c=event.clientY-320;0>c&&(c=0);b.style.left=d+"px";b.style.top=c+"px";b.style.zIndex="20";document.getElementById("lstprdart").innerHTML=a;processar("aqp","b")}function clsplst(){document.getElementById("cmplstprd").style.display="none"}
function lmp_vend_nv(){try{document.getElementById("vend_tp").value="NA",document.getElementById("vend_cat").value="NA",document.getElementById("vend_quant").value="",document.getElementById("vend_art").value="NA",document.getElementById("vend_pcod").value="",document.getElementById("vend_cbar").value="",document.getElementById("vend_prc").value="0.00"}catch(a){}}
function lmp_vend_nv2(){try{document.getElementById("pedvend_tp").value="NA",document.getElementById("pedvend_cat").value="NA",document.getElementById("pedvend_quant").value="",document.getElementById("pedvend_art").value="NA",document.getElementById("pedvend_prc").value="0.00"}catch(a){alert(a.message)}}function retinfpurc(){"0"===glbpurc&&(addEvntforCodeInptC(),processar("c","b"))}function retinfexp(){"0"===glbexp&&processar("d","b")}function retinfdshb(){"0"===glbdshb&&processar("dhs","b")}
function retinggu(){"0"===glbgu&&processar("gu","b")}function retinfva(){"0"===glbva&&processar("va","b")}function retinfest(){"0"!==glbest&&"yes"!==stckupd3||processar("est","b")}function retdpst(){"0"===glbdpst&&processar("dpst","b")}function retinv(){"0"===glbv&&(addEvntforCodeInptV(),glbv="1")}function retinpedv(){"0"===glbpedv&&(addEvntforCodeInptPedV(),glbpedv="1")}
function sumvaluesforeachtbl(a){try{if("d"===a){for(var b=0,d=document.getElementById("tbdvrd"),c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[2].innerHTML);b=b.toFixed(2);document.getElementById("tbdvrdsum").innerHTML="Total: "+b+" Mts"}else if("c"===a){b=0;d=document.getElementById("tbdvrc");for(c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[8].innerHTML);b=b.toFixed(2);var e=0,f=0;for(c=1;c<d.rows.length;c++)f=c,e+=parseFloat(d.rows[c].cells[12].innerHTML);e=e.toFixed(2);document.getElementById("tbdvrcsum").innerHTML=
"Total: "+b+" Mts, Lucro(est): "+e+" Mts, Registos: "+f}else if("va"===a){e=b=0;d=document.getElementById("tbdvrva");for(c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[10].innerHTML),e+=parseFloat(d.rows[c].cells[11].innerHTML);b=b.toFixed(2);e=e.toFixed(2);document.getElementById("tbdvrvasum").innerHTML="Total: "+b+" Mts, Lucro(est): "+e+" Mts"}else if("v"===a){b=0;d=document.getElementById("tbdvrv");for(c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[8].innerHTML);smvlsglb=b=b.toFixed(2);
document.getElementById("tbdvrvsum").innerHTML="Total: "+b+" Mts, Pago: <input type='number' id='pago' min='0' style='width: 90px;' onkeyup='calculatechg()' onchange='calculatechg()'>, Troco:<span id='troco' style='color: white;'></span> Mts"}else if("pedartins"===a){b=0;d=document.getElementById("dvrpedartins2");for(c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[8].innerHTML);b=b.toFixed(2);document.getElementById("pedtbdvrvsum").innerHTML="Total: "+b+" Mts";deleterped()}else if("dpst"===
a){a=e=b=0;d=document.getElementById("tbdvdpst");f=0;for(c=1;c<d.rows.length;c++)f+=1,b+=parseFloat(d.rows[c].cells[7].innerHTML),e+=parseFloat(d.rows[c].cells[8].innerHTML),a+=parseFloat(d.rows[c].cells[9].innerHTML);b=b.toFixed(2);document.getElementById("tbdvrdptsum").innerHTML="Total Deposito: "+FixDecToTwo(b)+" Mts, Total Usado: "+FixDecToTwo(e)+" Mts, <strong>Total Saldo: "+FixDecToTwo(a)+" Mts</strong>, Registos: "+f;deleterped()}}catch(g){}}
function sumvaluesforeachtbl2(a){try{if("d"===a){for(var b=0,d=document.getElementById("tbdvrd"),c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[2].innerHTML);b=b.toFixed(2);document.getElementById("tbdvrdsum").innerHTML="Total: "+b+" Mts"}else if("c"===a){b=0;d=document.getElementById("tbdvrc");d.getElementsByTagName("tr");for(c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[8].innerHTML);b=b.toFixed(2);var e=0;a=0;for(c=1;c<d.rows.length;c++)a=c,e+=parseFloat(d.rows[c].cells[12].innerHTML);
e=e.toFixed(2);document.getElementById("tbdvrcsum").innerHTML="Total: "+b+" Mts, Lucro(est): "+e+" Mts, Registos: "+a}else if("va"===a){e=b=0;d=document.getElementById("tbdvrva");for(c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[10].innerHTML),e+=parseFloat(d.rows[c].cells[11].innerHTML);b=b.toFixed(2);e=e.toFixed(2);document.getElementById("tbdvrvasum").innerHTML="Total: "+b+" Mts, Lucro(est): "+e+" Mts"}else if("v"===a){b=0;d=document.getElementById("tbdvrv");for(c=1;c<d.rows.length;c++)b+=
parseFloat(d.rows[c].cells[8].innerHTML);smvlsglb=b=b.toFixed(2);document.getElementById("tbdvrvsum").innerHTML="Total: "+b+" Mts, Pago: <input type='number' id='pago' min='0' style='width: 90px;' onkeyup='calculatechg()' onchange='calculatechg()'>, Troco:<span id='troco' style='color: white;'></span> Mts"}else if("pedartins"===a){b=0;d=document.getElementById("dvrpedartins2");for(c=1;c<d.rows.length;c++)b+=parseFloat(d.rows[c].cells[8].innerHTML);b=b.toFixed(2);document.getElementById("pedtbdvrvsum").innerHTML=
"Total: "+b+" Mts";deleterped()}}catch(f){}}function lgc(a){if("v"===a){a=document.getElementById("vend_tp").value;var b=document.getElementById("vend_cat").value;"Comida"===a&&"Alcool"===b&&alert("Escolheu COMIDA e ALCOOL, retificar!")}}function vartp(){return"&pt="+document.getElementById("vend_cat").value+"&z=a&q=0"}function vartp2(){return"&pt="+document.getElementById("pedvend_cat").value+"&z=a&q=0"}
function vprc(){var a=document.getElementById("vend_art").value;var b=document.getElementById("vend_quant").value;return"&pt="+a+"&z=b&q="+b}function vprc2(){var a=document.getElementById("pedvend_art").value;var b=document.getElementById("pedvend_quant").value;return"&pt="+a+"&z=b&q="+b}function vant(){return""}function limpar(){document.getElementById("di").value="";document.getElementById("df").value=""}
function rfrsh_vnd(){tblvd="<table border='1' id='tbdvrv'><tr style='height: 46px; background-color:  #9B00FF;background: linear-gradient(to bottom, #9B00FF, white);'><th>Ordem</th><th>Grupo</th><th>Prod C&oacute;digo</th><th>C&oacute;digo de Barra</th><th>Tipo</th><th>Categoria</th><th>Artigo</th><th>Quantidade</th><th>Pre&ccedil;o</th><th>Remo&ccedil;&atilde;o</th></tr>";vndits.forEach(rfshtbl);tblvd+="</table>";document.getElementById("tblvn").innerHTML=tblvd}
function rfshtbl(a,b,d){if("NA"!==a){d=b;b+=1;a=a.replace(":","");b="<td>"+b+"</td>";a=a.split(",");for(var c=1;c<a.length;c++){var e=a.length;e-=5;if(c===e)break;e=a[c].split("=")[1];b+="<td>"+e+"</td>"}b+="<td>"+crtbtn("rmvitvend("+d+")")+"</td>";tblvd+="<tr>"+b+"</tr>"}}
function crtbtn(a){return'                                <div style="padding-left: 10px; display: inline-block; width: 40px; height: 40px; border-radius: 50%;">\n                                    <a href="#" onclick="'+a+'" style="text-decoration: none; float: none; display: inline;">\n                                        <img src="/SGRB/img/rmvp.png" style="width: 32px; height: 32px;" title="Remover">\n                                    </a>\n                                </div>'}
function crtbtnopn(a){return'                                <div style="padding-left: 10px; background-color: white; display: inline-block; width: 40px; height: 40px; border-radius: 50%;">\n                                    <a href="#" onclick="'+a+'" style="text-decoration: none; float: none; display: inline;">\n                                        <img src="/SGRB/img/openp.png" style="width: 32px; height: 32px;" title="Abrir">\n                                    </a>\n                                </div>'}
function crtbtnedt(a){return'                                <div style="padding-left: 10px; background-color: white; display: inline-block; width: 40px; height: 40px; border-radius: 50%;">\n                                    <a href="#" onclick="'+a+'" style="text-decoration: none; float: none; display: inline;">\n                                        <img src="/SGRB/img/editp.png" style="width: 32px; height: 32px;" title="Editar">\n                                    </a>\n                                </div>'}
function filltbl(a,b){var d=b;"gu"===b?b=hus:"gvp"===b?b=hvp:"d"===b?b=hds:"c"===b?b=hcm:"ci"===b?b=hcmi:"va"===b?b=hva:"aqp"===b?b=artqp:"prodl"===b?b=plst:"est"===b?b=estp:"pedartins"===b?b=hva2:"fctry"===b?b=fcty:"dpst"===b&&(b=hdpst);var c="";try{c=b.replace("</table>","")}catch(l){}b="";a=a.split(":");for(var e=0;e<a.length;e++){var f=a[e].split(";");if(null!==f[1]&&""!==f[1]&&"undefined"!==f[1]&&"undefined"!==typeof f[1]){f=a[e].split(";");b="1"===f[f.length-3]&&"1"!==f[f.length-2]?"est"===
d?b+"<tr>":b+"<tr style='background-color: #F9E79F;'>":"1"===f[f.length-2]?"gu"===d?"1"===f[f.length-2]?b+"<tr>":"est"===d?b+"<tr>":b+"<tr style='background-color: #F1948A;'>":"est"===d?b+"<tr>":b+"<tr style='background-color: #F1948A;'>":b+"<tr>";for(var g=0;g<f.length;g++){var h=f[g];g===f.length-1&&("gu"===d?(h='<button type="button" id="btnusredit'+f[0]+'" class="btn btn-primary" onclick="alwupdt(\''+f[0]+'\')" style="background-color: #58D68D;">Abrir</button><button type="button" class="btn btn-primary" onclick="processar(\''+
f[0]+"','edc')\" style=\"background-color: #5DADE2;\">Editar</button>",h=""+crtbtnopn("alwupdt('"+f[0]+"')")+crtbtnedt("processar('"+f[0]+"','edc')")):"dpst"!==d&&(h=""+crtbtn("rmrrg('"+d+"','"+f[0]+"','"+f[f.length-3]+"')")));b=g===f.length-2||g===f.length-3||g===f.length-4?b+("<td id='guid"+f[0]+g+"'>"+h+"</td>"):"gvp"===d&&6===g?b+("<td><a href='#' onclick=\"chmrcmplstprdpz('"+f[6]+"')\">"+h+"</a></td>"):"dpst"===d&&1===g?b+("<td><a href='#' onclick=\"dpstclient('"+f[0]+"')\">"+f[1]+"</a></td>"):
"est"===d?b+("<td>"+f[g]+"</td>"):b+("<td>"+h+"</td>")}b+="</tr>"}}try{var k=c.replace("<tbody>","");c=k}catch(l){}try{c=k=c.replace("</tbody>","")}catch(l){}try{c=k=c.replace("</table>","")}catch(l){}c=c+b+"</table>";document.getElementById("dvr"+d).innerHTML="";document.getElementById("dvr"+d).innerHTML=c;"c"===d&&"0"===glbpurc2&&(glbpurc2="1",setTimeout(function(){processar("ci","b")},500));"gu"===d&&"0"===glbgvp&&(glbgvp="1",setTimeout(function(){processar("gvp","b")},500));"gvp"===d&&"0"===glbprodl&&
(glbprodl="1",setTimeout(function(){processar("prodl","b")},500));"prodl"===d&&"0"===glbfctry&&(glbfctry="1",setTimeout(function(){processar("fctry","b")},500));setTimeout(function(){sumvaluesforeachtbl(d)},500)}function prv(a){var b="";try{b=document.getElementById("lstprdart").innerHTML}catch(c){b="a"}var d="";try{d=document.getElementById("msnmbr").innerHTML}catch(c){d="a"}a="&prv="+a+"&id="+b+"&id2="+d+"&id3="+reqnmber;reqnmber="a";return a}
function reg_venda(){vndits.forEach(lstrvn);var a="&rgvn="+nvlst;nvlst="";a=a+"&id4="+reqnmber2;reqnmber2="a";return a}function lstrvn(a,b,d){nvlst+=""+a}function artprodlst(){var a=document.getElementById("produtolstart").value,b=document.getElementById("quantidadelstart").value,d="";try{d=document.getElementById("lstprdart").innerHTML}catch(c){d="a"}return"&art="+d+"&prod="+a+"&quant="+b}function prodlst(){var a=bsccaresp(document.getElementById("prodnvl").value);lstart2=a;return"&prod="+a}
function rmvitvend(a){vndits[a]="NA";rfrsh_vnd();document.getElementById("dvrst").innerHTML="<span style='color: green;'>Venda removida!</span>"}
function nvc(a){if("tblvn"===a){var b=document.getElementById("clientanome").value,d=document.getElementById("idc").innerHTML;if(null===d||""===d||"undefined"===typeof d||2>d.trim().length)alert("Criar novo cliente!");else if(null===b||""===b||"undefined"===typeof b||2>b.trim().length)alert("Prencher nome do cliente!");else try{document.getElementById(a).style.display="block","pedidonv"===a&&retinpedv()}catch(c){}}else try{document.getElementById(a).style.display="block","pedidonv"===a&&retinpedv()}catch(c){}if("vendcnv"===
a){try{document.getElementById("btnaddarts").disabled=!0}catch(c){}document.getElementById("spvendtp").innerHTML="Venda normal!";document.getElementById("spvendtp").style.color="blue";"c"===slsalc?(document.getElementById("spvendtp").innerHTML="Aloca&ccedil;&otilde;es!",document.getElementById("spdescount").innerHTML="Stock:<input type='number' id='txtstck' min='1' max='10' style='width: 80px;'/>"):document.getElementById("spdescount").innerHTML=""}if("comnv"===a)try{document.getElementById("btnnvc").disabled=
!0}catch(c){}else if("comnvinv"===a)try{document.getElementById("btnnvci").disabled=!0}catch(c){}else if("desnv"===a)try{document.getElementById("btnnvd").disabled=!0}catch(c){}else if("usnv"===a)try{document.getElementById("btnnvusr").disabled=!0}catch(c){}else if("prdnv"===a)try{document.getElementById("btnnvprd").disabled=!0}catch(c){}else if("fctrynv"===a)try{document.getElementById("btnnvfctry").disabled=!0}catch(c){}else if("vendnv"===a)try{document.getElementById("btnnvvp").disabled=!0}catch(c){}else if("dtnv"===
a)try{document.getElementById("btnnvdt").disabled=!0}catch(c){}}
function vendprec_nv(){var a=document.getElementById("vendprec_tp").value,b=document.getElementById("vendprec_cat").value,d=document.getElementById("vendprec_quant").value,c=document.getElementById("vendprec_art").value,e=document.getElementById("vendprec_prc").value,f=document.getElementById("vendprec_grp").value,g=document.getElementById("vendprec_pcod").value,h=document.getElementById("vendprec_cbar").value;lstart=""+c;return"&vpt="+a+"&vpc="+b+"&vpq="+d+"&vpa="+c+"&vpp="+e+"&vpg="+f+"&vpcod="+
g+"&vpcbar="+h}function usuar_nv(){var a=bsccaresp(document.getElementById("usu_us").value),b=bsccaresp(document.getElementById("usu_nms").value),d=bsccaresp(document.getElementById("usu_ap").value),c=document.getElementById("usu_cat").value,e=bsccaresp(document.getElementById("usu_priv").value);return"&usu="+a+"&usn="+b+"&usa="+d+"&usc="+c+"&usp="+e}
function desp_nv(){var a=document.getElementById("desp_tp").value,b=document.getElementById("desp_vl").value,d=document.getElementById("desp_dt").value,c=bsccaresp(document.getElementById("desp_ob").value);return"&dst="+a+"&dsv="+b+"&dsd="+d+"&dso="+c}
function comp_nv(){var a=document.getElementById("comp_tp").value,b=document.getElementById("comp_cat").value,d=document.getElementById("comp_quant").value,c=document.getElementById("comp_art").value,e=document.getElementById("comp_prec").value,f=document.getElementById("comp_grp").value,g=document.getElementById("comp_pcod").value,h=document.getElementById("comp_cbar").value,k=document.getElementById("comp_oprec").value,l=document.getElementById("comp_prz").value,m=document.getElementById("comp_oprectp").value,
n=document.getElementById("comp_lot").value;return"&cmt="+a+"&cmc="+b+"&cmq="+d+"&cma="+c+"&cmp="+e+"&cmg="+f+"&cmpcod="+g+"&cmcbar="+h+"&comp_oprec="+k+"&comp_oprectp="+m+"&comp_prz="+l+"&comp_lot="+n}
function comp_nvinv(){var a=document.getElementById("comp_tpinv").value,b=document.getElementById("comp_catinv").value,d=document.getElementById("comp_quantinv").value,c=document.getElementById("comp_artinv").value,e=document.getElementById("comp_precinv").value,f=document.getElementById("comp_grpinv").value,g=document.getElementById("comp_pcodinv").value,h=document.getElementById("comp_cbarinv").value;return"&cmt="+a+"&cmc="+b+"&cmq="+d+"&cma="+c+"&cmp="+e+"&cmg="+f+"&cmpcod="+g+"&cmcbar="+h+"&pcsartcnt="+
lstpurcqty}
function vend_nv(){var a=document.getElementById("vend_tp").value,b=document.getElementById("vend_cat").value,d=document.getElementById("vend_quant").value,c=document.getElementById("vend_art").value,e=document.getElementById("vend_prc").value,f=""+document.getElementById("idc").innerHTML,g=document.getElementById("clientanome").value,h=document.getElementById("vend_grp").value,k=document.getElementById("vend_pcod").value,l=document.getElementById("vend_cbar").value,m="";try{m=document.getElementById("txtstck").value}catch(n){m=""}"c"!==
slsalc&&(m="");"c"===slsalc&&(e="0.00");try{0>Number(e)&&(d="0")}catch(n){}return",vg="+h+",pcod="+k+",pcbar="+l+",vt="+a+",vc="+b+",va="+c+",vq="+d+",vp="+e+",clt="+f+",nm="+g+",pcsartcnt="+lstpurcqty+",txtstck="+m+",slsalc="+slsalc+":"}
function vendary(){if("1"===gbtninsrtvend)return desabledelement(),!1;var a=document.getElementById("vend_tp").value,b=document.getElementById("vend_cat").value,d=document.getElementById("vend_quant").value,c=document.getElementById("vend_art").value,e=document.getElementById("vend_prc").value;document.getElementById("vend_grp");var f=document.getElementById("vend_pcod").value,g=document.getElementById("vend_cbar").value,h="";try{h=document.getElementById("txtstck").value}catch(k){h=""}"NA"===a||
"NA"===b||"0"===d||"NA"===c||"0.0"===e||""===f||""===g?document.getElementById("dvrst").innerHTML="<span style='color: red;'>Todos os campos devem estar prenchidos!</span>":"c"!==slsalc||null!==h&&""!==h&&"undefined"!==typeof h?(vndits[vndits.length]=vend_nv(),rfrsh_vnd(),document.getElementById("dvrst").innerHTML="<span style='color: green;'>Venda adicionada!</span>",lmp_vend_nv(),sumvaluesforeachtbl("v")):document.getElementById("dvrst").innerHTML="<span style='color: red;'>Todos os campos devem estar prenchidos!</span>"}
function frmrqst(a){return'<div id="rsqst" class="inline" style="width: 120px; height: 74px; padding: 20px;" onclick="setbz(\''+a+'\')">            <div class="plcs1">                <div style=\'float: right; padding: 16px;\'><span style="font-size: 12px;" id="mstm'+a+'"></span><br><span id="msst'+a+'">Livre</span></div>                <div class="plcs2" id="msnmb'+a+'">                    <div style="padding-left: 6px;">                        Cliente<br><span style="font-size: 30px; font-weight: bold;">'+
a+'</span><br><span id="usrms'+a+'"></span>                    </div>                </div>            </div>        </div>'}
function gnrtplcs(){var a="";try{for(var b=1;b<noftbls;b++)a+=frmrqst(b)+'<div class="inline" style="width: 160px; height: 168px;"></div>'}catch(d){}try{document.getElementById("dvrmss").innerHTML=a+'<br><br>                   <div style="float: botton; width: 40px; height: 40px; border-radius: 50%;">\n                                    <a href="#" onclick="window.scrollTo(0, 0);" style="text-decoration: none; float: none; display: inline;">\n                                        <img src="/SGRB/img/gotop.png" style="width: 32px; height: 32px;" title="Ir ao topo">\n                                    </a>\n                                </div>'}catch(d){}try{document.getElementById("msnmbr").innerHTML=zz}catch(d){}}
function rstc(){if(4===requestc.readyState){var a=requestc.responseText.split(":");try{for(var b=0;b<noftbls;b++){var d=a[b];if(null!==d.split(";")[1]&&""!==d.split(";")[1]){var c=d.split(";")[0],e=d.split(";")[1],f=e,g="";"empty"===e?(e="Livre",g="#1D8348"):"pending"===e?(e="Pendente",g="#F5B041"):e.includes("_")&&(e="Ocupado",g="#DC7633");var h="";try{h=f.split("_")[0]}catch(k){}if("empty"===f||"pending"===f)f="";if("empty"===h||"pending"===h)h="";document.getElementById("msst"+c).innerHTML=e;document.getElementById("usrms"+
c).innerHTML=h;document.getElementById("msnmb"+c).style.backgroundColor=g;document.getElementById("mstm"+c).innerHTML=f}}}catch(k){}}};
